set allow-duplicate-recipes := true
set ignore-comments := true

_default:
    #!/usr/bin/bash
    /usr/bin/just --list --list-heading $'Available commands:\n' --list-prefix $' - '

# Imports
import "just/system.just"
