name: fedora-lk-cosmic
description: Custom Fedora COSMIC image based on uBlue, built with BlueBuild. (My personal, with NVIDIA support)

base-image: ghcr.io/lorduskordus/fedora-base-cosmic-nvidia
image-version: main

modules:

  # Common
  - from-file: common/config.yml
  
  # COSMIC
  #- from-file: cosmic/config.yml
