name: fedora-lk-kde
description: Custom Fedora KDE image based on uBlue, built with BlueBuild. (My personal, with NVIDIA support)

base-image: ghcr.io/lorduskordus/fedora-base-kde-nvidia
image-version: coreos

modules:

  # Common
  - from-file: common/config.yml
  
  # KDE
  #- from-file: kde/config.yml

  # Temporarily install COSMIC DE
  - from-file: common/addons/cosmic-desktop.yml
