modules:

  - type: rpm-ostree
    install:
      # Needed for Pano clipboard.
      - libgda
      - libgda-sqlite

  - type: files
    files:
      - gnome/usr: /usr

  - type: script
    scripts:
      - custom-gnome-shell.sh