name: fedora-lk-kde
description: Custom BlueBuild KDE image. (My personal, with NVIDIA support)

base-image: ghcr.io/lorduskordus/fedora-generic-kde-nvidia
image-version: latest

modules:

  # Common
  - from-file: image_configs/common.yml
  
  # KDE
  #- from-file: image_configs/kde.yml