name: fedora-lk-gnome
description: Custom Fedora GNOME image based on uBlue, built with BlueBuild. (My personal, with NVIDIA support)

base-image: ghcr.io/lorduskordus/fedora-base-gnome-nvidia
image-version: latest

modules:

  # Common
  - from-file: image_configs/common.yml
  
  # GNOME
  - from-file: image_configs/gnome.yml