name: fedora-lk-gnome
description: Custom BlueBuild GNOME image. (My personal, with NVIDIA support)

base-image: ghcr.io/lorduskordus/fedora-generic-gnome-nvidia
image-version: latest

modules:

  # Common
  - from-file: image_configs/common.yml
  
  # GNOME
  - from-file: image_configs/gnome.yml