modules:

  - type: files
    files:
      - source: system/gnome
        destination: /

  - type: gnome-extensions
    install:
      - Brightness control using ddcutil
      - Fullscreen Notifications
