name: fedora-lk-gnome
description: Customized Fedora GNOME Atomic

base-image: ghcr.io/lorduskordus/fedora-base-gnome-nvidia
image-version: latest

modules:

  - from-file: common/config.yml
  - from-file: gnome/config.yml

  # Temporarily install COSMIC DE
  - from-file: common/addons/cosmic-desktop.yml
