type: default-flatpaks
configurations:
  - scope: system
    notify: false
    repo:
      url: https://dl.flathub.org/repo/flathub.flatpakrepo
      name: flathub
      title: Flathub
    install:
      - com.brave.Browser
      - org.torproject.torbrowser-launcher
      - com.vysp3r.ProtonPlus
      - tv.plex.PlexDesktop
