type: dnf
repos:
  files:
    - vscode.repo
    - unityhub.repo
    - https://download.docker.com/linux/fedora/docker-ce.repo
    - https://brave-browser-rpm-release.s3.brave.com/brave-browser.repo
  keys:
    - https://brave-browser-rpm-release.s3.brave.com/brave-core.asc
    - https://packages.microsoft.com/keys/microsoft.asc
    - https://hub.unity3d.com/linux/repos/rpm/stable/repodata/repomd.xml.key
  copr:
    # F42 doesn't have eza, this COPR does
    - alternateved/eza
optfix:
  - brave.com
  - unityhub
install:
  packages:
    - virt-manager

    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin

    - fish
    - bat
    - eza

    - ddcutil
    - xeyes
    - android-tools
    - telnet
    - nmap
    - wireshark
    - syncthing
    
    - code
    - unityhub
    - brave-browser

    - steam
    - lutris
    - mangohud
    - goverlay
