modules:

  - type: rpm-ostree
    source: ghcr.io/lorduskordus/bluebuild-modules
    repos:
      - https://download.docker.com/linux/fedora/docker-ce.repo
    install:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
  
  - type: systemd
    system:
      enabled:
        - docker.service
