modules:

  - type: rpm-ostree
    source: ghcr.io/lorduskordus/bluebuild-modules
    install:
      - fish

  - type: hide-app-launchers
    source: ghcr.io/lorduskordus/bluebuild-modules
    hide:
      - fish
