type: rpm-ostree
source: ghcr.io/lorduskordus/bluebuild-modules
repos:
  - vscode.repo
  - unityhub.repo
keys:
  - https://packages.microsoft.com/keys/microsoft.asc
  - https://hub.unity3d.com/linux/repos/rpm/stable/repodata/repomd.xml.key
optfix:
  - unityhub
install:
  - code
  - unityhub
  - xeyes
  - android-tools
  - telnet
  - wireshark
  - virt-manager
  - syncthing
  - ddcutil
  - bat
  - eza
