modules:

  - type: bling
    install:
      - rpmfusion

  - type: akmods
    base: bazzite
    install:
      - VirtualBox

  - type: rpm-ostree
    source: ghcr.io/lorduskordus/bluebuild-modules
    install:
      - VirtualBox
